<?xml version="1.0" encoding="ISO-8859-1"?>

<xsl:stylesheet version="1.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

<xsl:template match="/">
  <html>
    <head>
    <link type="text/css" rel="stylesheet" 
          href="traverse.css" />
    <script type="text/javascript" src="traverse_frames.js">
    </script>
    </head>
  <body onload='collapseAll();'>
  <xsl:apply-templates/>
  </body>
  </html>
</xsl:template>


<xsl:template match="gen_date">
<address>Generated by <a href="http://www.cadence.com/products/cic/schematic_editor/pages/default.aspx" target="_blank">Virtuoso Schematic Editor</a>. on <xsl:value-of select="."/></address>

</xsl:template>

<xsl:template match="bom">
<!-- skip bom entirely within the nav frame -->
</xsl:template>


<xsl:template match="bom_entry">
<!-- skip bom entirely within the nav frame -->
</xsl:template>

<xsl:template match="master_details">
<!-- skip master details entirely within the nav frame -->
</xsl:template>

<xsl:template match="top">
<!-- skip master details entirely within the nav frame -->
</xsl:template>



<xsl:template match="occurrence_tree">
  <h1>Navigator</h1>
    <ul id="top_list_item_ul"><li  id="top_list_item_li"><span style="white-space: nowrap;">
    <a href="#nowhere" onclick="toggleBullet(this.parentNode, this)">[+]</a> 
    <xsl:for-each select="//top">
    <xsl:element name="span">
      <xsl:attribute name="class">hotspot</xsl:attribute>
      <xsl:attribute name="onmouseover">
        setBigIMG('<xsl:value-of select="image256"/>');
      </xsl:attribute>
      <xsl:attribute name="onmouseout">
        setBigIMG("images/barbaLib/truc/schematic/thumbnail_256x256.png");
      </xsl:attribute>
        <xsl:element name="a">
          <xsl:attribute name="onclick">centerJumpTo('top_cell');
          </xsl:attribute>
        Top Cell
        </xsl:element> <!-- anchor, a -->
    </xsl:element> <!-- span -->
  :(
  <xsl:apply-templates select="lib"/>
  ,
  <xsl:apply-templates select="cell"/>
  ,
  <xsl:apply-templates select="view"/>
  )
 
    </xsl:for-each> <!-- //top -->
    </span>
  <!-- now do the real occ tree -->
  <xsl:apply-templates select="occ"/>
  </li></ul>
</xsl:template>


<xsl:template match="occ">
  <ul style="margin-left: -20px;">
  <li style="white-space: nowrap;">
  <xsl:if test="children > 0">
    <a href="#nowhere" onclick="toggleBullet(this.parentNode, this)">[+]</a> 
  </xsl:if>
  <xsl:apply-templates select="indent"/>
    <xsl:element name="span">
      <xsl:attribute name="class">hotspot</xsl:attribute>
      <xsl:attribute name="onmouseover">
        setBigIMG('<xsl:value-of select="thumbnail256"/>');
      </xsl:attribute>
      <xsl:attribute name="onmouseout">
        setBigIMG("images/barbaLib/truc/schematic/thumbnail_256x256.png");
      </xsl:attribute>
        <xsl:element name="a">
          <xsl:attribute name="onclick">centerJumpTo('<xsl:value-of select="refid"/>');
          </xsl:attribute>
        <xsl:apply-templates select="inst"/>
        </xsl:element> <!-- anchor, a -->
    </xsl:element> <!-- span -->
  :(
  <xsl:apply-templates select="lib"/>
  ,
  <xsl:apply-templates select="cell"/>
  ,
  <xsl:apply-templates select="view"/>
  )
  </li>
  <xsl:apply-templates select="occ"/>
  </ul>
</xsl:template>

<xsl:template match="indent">
<!-- TODO delete me...indents are not needed -->
</xsl:template>


<xsl:template match="inst">
        <xsl:value-of select="."/>
</xsl:template>

<xsl:template match="lib">
        <xsl:value-of select="."/>
</xsl:template>

<xsl:template match="cell">
        <xsl:value-of select="."/>
</xsl:template>

<xsl:template match="view">
        <xsl:value-of select="."/>
</xsl:template>


</xsl:stylesheet>
